test: fix retry on int-test
Summary:
Did you know that if returns 0 as its return value? I didn't then. I do
now.

Test Plan:
Running this locally until trivvy fails.

diff --git a/bin/bix-elixir b/bin/bix-elixir
--- a/bin/bix-elixir
+++ b/bin/bix-elixir
@@ -16,24 +16,35 @@ do_int_test() {
     bi_pushd platform_umbrella/apps/verify
     mix "do" deps.get, compile --warnings-as-errors >/dev/null
 
-    # Exit code 1: compilation failed, Exit code 2: tests failed
-    if ! mix test --trace --warnings-as-errors --all-warnings --only cluster_test "$@"; then
-        local exit_code=$?
-        if [[ $exit_code = 2 ]]; then
-            log "Some tests failed, retrying with --failed flag after a short wait..."
-            sleep 120
+    local err
 
-            log "Retrying failed tests..."
-            mix test --trace --warnings-as-errors --all-warnings --only cluster_test --failed "$@"
-        else
-            # Compilation failed or other error, don't retry
-            bi_popd
-            die "Elixir integration tests ${RED}Failed${NOFORMAT}" "$exit_code"
-        fi
-    fi
+    {
+        run_int_test "$@"
+        err="$?"
+    } || true
+
+    # Exit code 1: compilation failed, Exit code 2: tests failed
+    case $err in
+    0)
+        log "Elixir integration tests ${GREEN}Passed${NOFORMAT}"
+        ;;
+    2)
+        log "Some tests failed, retrying with --failed flag after a short wait..."
+        sleep 120
+
+        log "Retrying failed tests..."
+        run_int_test --failed "$@"
+        ;;
+    *)
+        die "Elixir integration tests ${RED}Failed${NOFORMAT} with exit code $err" "$err"
+        ;;
+    esac
 
     bi_popd
-    log "Elixir integration tests ${GREEN}Passed${NOFORMAT}"
+}
+
+run_int_test() {
+    mix test --trace --warnings-as-errors --all-warnings --only cluster_test "$@"
 }
 
 do_test_deep() {
